### ISSUE TITLE
hi, can you creat textnow account now?

### ISSUE THREAD

**Issue by jimenggirl** [i-ght/TextPlusAndroidRevEngineered#1]
if you can, i want buy textnow account creator tool, 
my tg @WA888881234

**Comment by i-ght** [comment]
No

**Comment by jimenggirl** [comment]
ok thanks, can you give me your tg?

**Comment by i-ght** [comment]
No

**Comment by jimenggirl** [comment]
textplus can?
sorry ，I can pay for that if you interseting in it.

**Comment by jimenggirl** [comment]
i try fix your tools, but returns
![image](https://github.com/i-ght/TextPlusAndroidRevEngineered/assets/112556855/f0aec1c5-88f4-437c-9610-bcb530c06821)
