### ISSUE TITLE
sorry, i try fix your tools, but textnow return this error, do you know why?

### ISSUE THREAD

**Issue by jimenggirl** [i-ght/TextPlusAndroidRevEngineered#2]
![image](https://github.com/i-ght/TextPlusAndroidRevEngineered/assets/112556855/0a299f4f-a0b7-49ea-9ecc-be0010dad3e1)

I'm sorry to bother you again, I'm just trying to understand how to get it working again

**Comment by i-ght** [comment]
No, I don't know why.

To get it working again, you'd have to make a recording an android device running the app and compare the api calls the app makes to what this code is doing.

I won't be making any changes to this code

Good luck
